blank_issues_enabled: false
contact_links:
   - name: "Feature Request"
    about: "Suggest new features for Bidome"
    url: "https://github.com/Wave-Studio/BIDOME/discussions/categories/feature-requests"
  - name: "Translations"
    about: "Suggest/Comment on translations by the community"
    url: "https://crowdin.com/project/bidome"

  - name: "Discord Server"
    about: "Use this for general discussion and/or reporting Security Vulnerabilities"
    url: "https://discord.gg/yrwUpMcfcR"
  - name: "Guilded Server"
    about: "Use this for general discussion and/or reporting Security Vulnerabilities"
    url: "https://www.guilded.gg/i/k1bRxyyp?r=ndlwkYR4"